name: CI
on:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash -l {0}
jobs:
  style:
    runs-on: ubuntu-22.04
    container:
      image: dolfinx/dolfinx:stable
      options: --user 1001 --privileged 
    name: CI test
    steps:
      - name: run code
        uses: actions/checkout@v2
      - name: run the file
        run: mpirun -n 1 python3 -u test_file.py
      - name: change directory
        run: cd test_folder
      - name: produce output
        run: python3 ./test_script.py
        run: |
        print(python3 ./test_script.py)
